// Package ipdance provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package ipdance

// IPInfo defines model for IPInfo.
type IPInfo struct {
	// Asn The Autonomous System Number (ASN) followed by the associated organization for the IP address.
	Asn *string `json:"asn,omitempty"`

	// HttpProtocol The HTTP protocol version used by the IP address.
	HttpProtocol *string `json:"httpProtocol,omitempty"`

	// Ip The IP address being queried.
	Ip *string `json:"ip,omitempty"`

	// Location The geographic location associated with the IP address, including city, state, and country.
	Location *string `json:"location,omitempty"`

	// RegionCode The region code associated with the IP address.
	RegionCode *string `json:"regionCode,omitempty"`
}
